language: c

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake .. -DENABLE_COVERAGE=On

script:
  - make && make test
  - make gcov

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov